<?php

function getCards() {
    return [
        [
            "id" => 1,
            "name" => "George Washington",
            "image" => "../images/cards/george_washington.png",
            "description" => "Premier président des États-Unis (1789-1797), il a joué un rôle clé dans l'indépendance américaine et la fondation du pays.",
            "pts" => 30,
            "atk" => 3,
            "hp" => 6
        ],
        [
            "id" => 2,
            "name" => "Jules César",
            "image" => "../images/cards/jules_cesar.png",
            "description" => "Général et homme d'État romain, il a conquis la Gaule et contribué à la chute de la République romaine.",
            "pts" => 40,
            "atk" => 7,
            "hp" => 5
        ],
        [
            "id" => 3,
            "name" => "Cléopâtre",
            "image" => "../images/cards/cleopatre.png",
            "description" => "Dernière reine d'Égypte, célèbre pour son intelligence et ses alliances politiques avec César et Marc Antoine.",
            "pts" => 20,
            "atk" => 2,
            "hp" => 5
        ],
        [
            "id" => 4,
            "name" => "Albert Einstein",
            "image" => "../images/cards/albert_einstein.png",
            "description" => "Physicien théoricien à l'origine de la relativité, il a révolutionné notre compréhension du temps, de l'espace et de l'énergie.",
            "pts" => 30,
            "atk" => 1,
            "hp" => 4
        ],
        [
            "id" => 5,
            "name" => "Napoléon Bonaparte",
            "image" => "../images/cards/napoleon_bonaparte.png",
            "description" => "Empereur français et stratège militaire, il a marqué l'Europe par ses conquêtes et ses réformes comme le Code civil.",
            "pts" => 50,
            "atk" => 5,
            "hp" => 7
        ],
        [
            "id" => 6,
            "name" => "Léonard de Vinci",
            "image" => "../images/cards/leonard_de_vinci.png",
            "description" => "Génie de la Renaissance, artiste, inventeur et scientifique, connu pour la Joconde et ses nombreuses innovations.",
            "pts" => 30,
            "atk" => 2,
            "hp" => 5
        ],
        [
            "id" => 7,
            "name" => "Isaac Newton",
            "image" => "../images/cards/isaac_newton.png",
            "description" => "Mathématicien et physicien anglais, il a formulé les lois du mouvement et la théorie de la gravitation universelle.",
            "pts" => 30,
            "atk" => 1,
            "hp" => 4
        ],
        [
            "id" => 8,
            "name" => "Galilée",
            "image" => "../images/cards/galilee.png",
            "description" => "Astronome italien, pionnier de la méthode scientifique, il a défendu le modèle héliocentrique.",
            "pts" => 20,
            "atk" => 1,
            "hp" => 4
        ],
        [
            "id" => 9,
            "name" => "Marie Curie",
            "image" => "../images/cards/marie_curie.png",
            "description" => "Scientifique pionnière de la radioactivité, première femme à recevoir un prix Nobel et seule à en avoir deux dans des domaines différents.",
            "pts" => 30,
            "atk" => 1,
            "hp" => 5
        ],
        [
            "id" => 10,
            "name" => "Charles Darwin",
            "image" => "../images/cards/charles_darwin.png",
            "description" => "Naturaliste britannique, il a développé la théorie de l'évolution par sélection naturelle.",
            "pts" => 30,
            "atk" => 2,
            "hp" => 5
        ],
        [
            "id" => 11,
            "name" => "Alexandre le Grand",
            "image" => "../images/cards/alexandre_le_grand.png",
            "description" => "Roi de Macédoine, conquérant exceptionnel, il a créé un immense empire de la Grèce jusqu'à l'Inde.",
            "pts" => 50,
            "atk" => 6,
            "hp" => 8
        ],
        [
            "id" => 12,
            "name" => "Gengis Khan",
            "image" => "../images/cards/gengis_khan.png",
            "description" => "Chef mongol, il a fondé l'un des plus grands empires de l'histoire grâce à ses stratégies militaires.",
            "pts" => 50,
            "atk" => 6,
            "hp" => 8
        ],
        [
            "id" => 13,
            "name" => "Abraham Lincoln",
            "image" => "../images/cards/abraham_lincoln.png",
            "description" => "Président des États-Unis durant la guerre de Sécession, il a aboli l'esclavage et préservé l'unité du pays.",
            "pts" => 40,
            "atk" => 3,
            "hp" => 7
        ],
        [
            "id" => 14,
            "name" => "Winston Churchill",
            "image" => "../images/cards/winston_churchill.png",
            "description" => "Premier ministre britannique durant la Seconde Guerre mondiale, célèbre pour son leadership et ses discours.",
            "pts" => 40,
            "atk" => 3,
            "hp" => 7
        ],
        [
            "id" => 15,
            "name" => "Mahatma Gandhi",
            "image" => "../images/cards/mahatma_gandhi.png",
            "description" => "Leader de l'indépendance indienne, il a prôné la non-violence et la désobéissance civile.",
            "pts" => 20,
            "atk" => 1,
            "hp" => 6
        ],
        [
            "id" => 16,
            "name" => "Martin Luther King",
            "image" => "../images/cards/martin_luther.png",
            "description" => "Militant des droits civiques, il a lutté contre la ségrégation raciale aux États-Unis avec des actions pacifiques.",
            "pts" => 20,
            "atk" => 1,
            "hp" => 6
        ],
        [
            "id" => 17,
            "name" => "Nelson Mandela",
            "image" => "../images/cards/nelson_mandela.png",
            "description" => "Leader anti-apartheid et premier président noir d'Afrique du Sud, symbole de réconciliation.",
            "pts" => 40,
            "atk" => 3,
            "hp" => 8
        ],
        [
            "id" => 18,
            "name" => "Jules Verne",
            "image" => "../images/cards/jules_verne.png",
            "description" => "Écrivain français visionnaire, auteur de romans d'aventure et de science-fiction comme 'Vingt mille lieues sous les mers'.",
            "pts" => 20,
            "atk" => 1,
            "hp" => 4
        ],
        [
            "id" => 19,
            "name" => "Lénine",
            "image" => "../images/cards/lenine.png",
            "description" => "Révolutionnaire russe, il a dirigé la révolution de 1917 et fondé l'Union soviétique.",
            "pts" => 40,
            "atk" => 4,
            "hp" => 6
        ],
        [
            "id" => 20,
            "name" => "Franklin Roosevelt",
            "image" => "../images/cards/franklin_roosevelt.png",
            "description" => "Président américain durant la Grande Dépression et la Seconde Guerre mondiale, initiateur du New Deal.",
            "pts" => 40,
            "atk" => 3,
            "hp" => 7
        ],
        [
            "id" => 21,
            "name" => "Voltaire",
            "image" => "../images/cards/voltaire.png",
            "description" => "Philosophe des Lumières, défenseur de la liberté d'expression et critique de l'intolérance religieuse.",
            "pts" => 20,
            "atk" => 2,
            "hp" => 4
        ],
        [
            "id" => 22,
            "name" => "Jean-Jacques Rousseau",
            "image" => "../images/cards/jean_jacques_rousseau.png",
            "description" => "Philosophe influent, il a développé des idées sur la liberté, l'éducation et le contrat social.",
            "pts" => 20,
            "atk" => 2,
            "hp" => 4
        ],
        [
            "id" => 23,
            "name" => "Platon",
            "image" => "../images/cards/platon.png",
            "description" => "Philosophe grec, élève de Socrate, fondateur de l'Académie et auteur de nombreux dialogues.",
            "pts" => 30,
            "atk" => 2,
            "hp" => 5
        ],
        [
            "id" => 24,
            "name" => "Aristote",
            "image" => "../images/cards/aristote.png",
            "description" => "Philosophe grec, élève de Platon, il a influencé la logique, la science et la philosophie occidentale.",
            "pts" => 30,
            "atk" => 3,
            "hp" => 5
        ],
        [
            "id" => 25,
            "name" => "Socrate",
            "image" => "../images/cards/socrate.png",
            "description" => "Philosophe grec, maître de Platon, connu pour sa méthode de questionnement et sa recherche de la vérité.",
            "pts" => 30,
            "atk" => 2,
            "hp" => 5
        ],
        [
            "id" => 26,
            "name" => "Christophe Colomb",
            "image" => "../images/cards/christophe_colomb.png",
            "description" => "Navigateur italien, il a ouvert la voie aux explorations européennes vers les Amériques.",
            "pts" => 30,
            "atk" => 3,
            "hp" => 6
        ],
        [
            "id" => 27,
            "name" => "Marco Polo",
            "image" => "../images/cards/marco_polo.png",
            "description" => "Explorateur vénitien, célèbre pour ses voyages en Asie et ses récits détaillés.",
            "pts" => 30,
            "atk" => 3,
            "hp" => 5
        ],
        [
            "id" => 28,
            "name" => "Jeanne d'Arc",
            "image" => "../images/cards/jeanne_d_arc.png",
            "description" => "Héroïne française, elle a mené les troupes durant la guerre de Cent Ans et symbolise le courage.",
            "pts" => 40,
            "atk" => 5,
            "hp" => 7
        ],
        [
            "id" => 29,
            "name" => "Louis XIV",
            "image" => "../images/cards/louis_xiv.png",
            "description" => "Roi de France, surnommé le Roi Soleil, il a renforcé le pouvoir royal et construit Versailles.",
            "pts" => 40,
            "atk" => 3,
            "hp" => 7
        ],
        [
            "id" => 30,
            "name" => "Pascal Urso",
            "image" => "../images/cards/pascal_urso.png",
            "description" => "Professeur d'informatique à l'Université Côte d'Azur.",
            "pts" => 50,
            "atk" => 5,
            "hp" => 5
        ]
    ];
}

?>